[workspace]
members = [
    "c02_hello",
    "c02_actix-gcd",
    "c02_mandelbrot",
    "c02_quickreplace",
    "c03_example",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
hello = { path = "c02_hello" }
