[workspace]
members = [
    "c02/hello",
    "c02/actix-gcd",
    "c02/mandelbrot",
    "c02/quickreplace",
    "c03/example",
    "c04/ownership",
    "c04/os-move", "c04/copy-type",
]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
hello = { path = "c02/hello" }
