[package]
name = "async-chat"
version = "0.1.0"
edition.workspace = true

[dependencies]
async-std = { version = "1.13.2", features = ["unstable"] }
tokio = { version = "1.47.1", features = ["sync"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.142"
